# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#spring.thymeleaf.cache=false
#spring.main.show-banner=false
#logging.level.jdbc=OFF
#logging.level.jdbc.sqltiming=DEBUG
#logging.level.jdbc.resultsettable=DEBUG

# \u0397 \u03B4\u03B9\u03B5\u03CD\u03B8\u03C5\u03BD\u03C3\u03B7 \u03C4\u03B7\u03C2 \u03B2\u03AC\u03C3\u03B7\u03C2 \u03C3\u03BF\u03C5 (\u03BC\u03B5 \u03C4\u03BF \u03CC\u03BD\u03BF\u03BC\u03B1 \u03C0\u03BF\u03C5 \u03C4\u03B7\u03C2 \u03AD\u03B4\u03C9\u03C3\u03B5\u03C2 \u03C3\u03C4\u03BF SQL script)
spring.datasource.url=jdbc:mysql://localhost:3306/advanced_databases_project_2026?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false

# \u03A4\u03B1 \u03C3\u03C4\u03BF\u03B9\u03C7\u03B5\u03AF\u03B1 \u03C3\u03CD\u03BD\u03B4\u03B5\u03C3\u03B7\u03C2
spring.datasource.username=root
spring.datasource.password=root

# \u039F "\u03BF\u03B4\u03B7\u03B3\u03CC\u03C2" \u03C4\u03B7\u03C2 MySQL \u03B3\u03B9\u03B1 \u03C4\u03B7 Java
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# (\u03A0\u03C1\u03BF\u03B1\u03B9\u03C1\u03B5\u03C4\u03B9\u03BA\u03CC) \u0391\u03BD \u03B8\u03AD\u03BB\u03BF\u03C5\u03BC\u03B5 \u03C3\u03C4\u03BF \u03BC\u03AD\u03BB\u03BB\u03BF\u03BD \u03BD\u03B1 \u03B2\u03BB\u03AD\u03C0\u03BF\u03C5\u03BC\u03B5 \u03C4\u03B1 SQL queries \u03C3\u03C4\u03B7\u03BD \u03BA\u03BF\u03BD\u03C3\u03CC\u03BB\u03B1 \u03C4\u03BF\u03C5 Eclipse
spring.jpa.show-sql=true
